# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  # every day at 0:00UTC
  schedule:
  - cron: "0 0 * * *"

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python setup.py install
        
        
    - name: Generate config files
      run: |
        shreddit -g
    
    - name: See files
      run: |
        ls
        
    - name: Shreddit Credentials and config
      run: |
          echo "${{secrets.REDDIT_CREDENTIALS_FILE}}" > praw.ini
          echo "${{secrets.SHREDDIT_YAML}}" > shreddit.yml
          

   
    - name: run the script
      run: |
        shreddit
